const PUZZLES = [
  { word: "BRUNCH", a: "BREAKFAST", b: "LUNCH", clue: "A late-morning meal that does double duty" },
  { word: "SMOG", a: "SMOKE", b: "FOG", clue: "City air you can almost chew" },
  { word: "SPORK", a: "SPOON", b: "FORK", clue: "Picnic cutlery that can't quite decide what it is" },
  { word: "FRENEMY", a: "FRIEND", b: "ENEMY", clue: "Smiles to your face, talks behind your back" },
  { word: "MOTEL", a: "MOTOR", b: "HOTEL", clue: "Roadside lodging built for the road-tripper" },
  { word: "GLAMPING", a: "GLAMOUR", b: "CAMPING", clue: "Roughing it — with a proper bed and wifi" },
  { word: "STAYCATION", a: "STAY", b: "VACATION", clue: "A holiday taken without leaving home" },
  { word: "HANGRY", a: "HUNGRY", b: "ANGRY", clue: "The mood that hits when lunch is very late" },
  { word: "SKORT", a: "SKIRT", b: "SHORTS", clue: "Athletic bottoms that cover all bases" },
  { word: "NETIZEN", a: "INTERNET", b: "CITIZEN", clue: "A person who lives as much online as off" },
  { word: "WEBINAR", a: "WEB", b: "SEMINAR", clue: "A conference call dressed up as a lecture" },
  { word: "ROMCOM", a: "ROMANTIC", b: "COMEDY", clue: "The genre where two people always end up together" },
  { word: "EMOTICON", a: "EMOTION", b: "ICON", clue: "A little face typed from punctuation marks :-)" },
  { word: "GUESSTIMATE", a: "GUESS", b: "ESTIMATE", clue: "A rough figure pulled from thin air" },
  { word: "PODCAST", a: "IPOD", b: "BROADCAST", clue: "An audio show you download and play on demand" },
  { word: "GINORMOUS", a: "GIGANTIC", b: "ENORMOUS", clue: "Way, way bigger than big" },
  { word: "CHILLAX", a: "CHILL", b: "RELAX", clue: "What someone tells you when you're stressed out" },
  { word: "BROMANCE", a: "BROTHER", b: "ROMANCE", clue: "An intense but entirely platonic bond between two guys" },
  { word: "MOCKUMENTARY", a: "MOCK", b: "DOCUMENTARY", clue: "A fake doc that plays it completely straight" },
  { word: "WORKAHOLIC", a: "WORK", b: "ALCOHOLIC", clue: "Someone whose office is practically their home" },
  { word: "PHABLET", a: "PHONE", b: "TABLET", clue: "A screen so big it's barely a phone anymore" },
  { word: "MALWARE", a: "MALICIOUS", b: "SOFTWARE", clue: "Code designed to cause harm to your computer" },
  { word: "MOPED", a: "MOTOR", b: "PEDAL", clue: "A small two-wheeled vehicle you can also pedal" },
  { word: "JEGGINGS", a: "JEANS", b: "LEGGINGS", clue: "Stretchy pants that look just like denim" },
  { word: "BLOG", a: "WEB", b: "LOG", clue: "An online journal anyone can publish" },
  { word: "INFOMERCIAL", a: "INFORMATION", b: "COMMERCIAL", clue: "A late-night ad disguised as a TV programme" },
  { word: "BIOPIC", a: "BIOGRAPHY", b: "PICTURE", clue: "A film that tells the story of a real person's life" },
  { word: "DOCUDRAMA", a: "DOCUMENTARY", b: "DRAMA", clue: "A dramatized re-enactment of real events" },
  { word: "COSPLAY", a: "COSTUME", b: "PLAY", clue: "Dressing up as your favourite fictional character" },
  { word: "LISTICLE", a: "LIST", b: "ARTICLE", clue: "Online journalism that counts things out for you" },
  { word: "AFFLUENZA", a: "AFFLUENCE", b: "INFLUENZA", clue: "The malaise of having too much money and too little meaning" },
  { word: "ANTICIPOINTMENT", a: "ANTICIPATION", b: "DISAPPOINTMENT", clue: "That deflated feeling when the hype was bigger than the thing" },
  { word: "BADVERTISING", a: "BAD", b: "ADVERTISING", clue: "Marketing so cringeworthy it actually sticks in your head" },
  { word: "BEDGASM", a: "BED", b: "ORGASM", clue: "The overwhelming pleasure of finally lying down after a long day" },
  { word: "BINGE", a: "BENDER", b: "INGE", clue: "To watch episode after episode without stopping" },
  { word: "BLURT", a: "BLARE", b: "SPURT", clue: "To say something suddenly without thinking" },
  { word: "BOTNET", a: "ROBOT", b: "NETWORK", clue: "An army of hijacked computers doing a hacker's bidding" },
  { word: "BRAINIAC", a: "BRAIN", b: "MANIAC", clue: "Someone frighteningly clever — from a certain Man of Steel villain" },
  { word: "BREATHALYZER", a: "BREATH", b: "ANALYZER", clue: "A roadside device that tells police how much you've had to drink" },
  { word: "CAMCORDER", a: "CAMERA", b: "RECORDER", clue: "A handheld gadget that shoots home movies" },
  { word: "CARJACK", a: "CAR", b: "HIJACK", clue: "To steal a vehicle while the driver is still in it" },
  { word: "CHORTLE", a: "CHUCKLE", b: "SNORT", clue: "A gleeful, slightly undignified laugh — coined by Lewis Carroll" },
  { word: "CINEPLEX", a: "CINEMA", b: "COMPLEX", clue: "A large building housing many movie screens under one roof" },
  { word: "CLASP", a: "CLAMP", b: "GRASP", clue: "To hold something firmly shut or together" },
  { word: "CLASH", a: "CLAP", b: "CRASH", clue: "A loud, jarring collision or conflict" },
  { word: "CLUMP", a: "CLUSTER", b: "LUMP", clue: "A dense, irregular mass of things grouped together" },
  { word: "COMIXTAPE", a: "COMIC", b: "MIXTAPE", clue: "A self-published collection of illustrated stories" },
  { word: "CRAPTASTIC", a: "CRAP", b: "FANTASTIC", clue: "So terrible it wraps right back around to impressive" },
  { word: "CYBORG", a: "CYBERNETIC", b: "ORGANISM", clue: "A being that is part human, part machine" },
  { word: "DRAMEDY", a: "DRAMA", b: "COMEDY", clue: "A TV show that mixes laughs with genuine emotional weight" },
  { word: "EDUTAINMENT", a: "EDUCATION", b: "ENTERTAINMENT", clue: "Learning disguised as something fun enough to sit through" },
  { word: "ELECTROCUTE", a: "ELECTRIC", b: "EXECUTE", clue: "To kill or injure with an electric shock" },
  { word: "EMOJI", a: "EMOTION", b: "EMOJI", clue: "A tiny digital picture that says what words can't" },
  { word: "FANTABULOUS", a: "FANTASTIC", b: "FABULOUS", clue: "Beyond fantastic — even more fabulous than fabulous" },
  { word: "FLARE", a: "FLAME", b: "GLARE", clue: "A sudden burst of bright light used as a signal" },
  { word: "FLEECE", a: "FLOCK", b: "GREASE", clue: "To swindle someone out of their money" },
  { word: "FLUTTER", a: "FLY", b: "STUTTER", clue: "To move or beat with quick, light, irregular motion" },
  { word: "FOODIE", a: "FOOD", b: "GROUPIE", clue: "Someone who pursues culinary experiences with fan-like devotion" },
  { word: "FRANKENFOOD", a: "FRANKENSTEIN", b: "FOOD", clue: "Genetically modified produce with an alarming ring to it" },
  { word: "FREEMIUM", a: "FREE", b: "PREMIUM", clue: "A pricing model where basic is free and everything good costs extra" },
  { word: "FROGURT", a: "FROZEN", b: "YOGURT", clue: "A tangy, cold dessert sold as a healthier ice cream" },
  { word: "FROYO", a: "FROZEN", b: "YOGURT", clue: "The casual shorthand for a chilly, tangy dessert" },
  { word: "GASTROPUB", a: "GASTRONOMY", b: "PUB", clue: "A bar that takes its kitchen as seriously as its beer taps" },
  { word: "GERRYMANDER", a: "GERRY", b: "SALAMANDER", clue: "To redraw political districts in a way that rigs the outcome" },
  { word: "GLOBISH", a: "GLOBAL", b: "ENGLISH", clue: "A simplified form of English used across language barriers" },
  { word: "GREENWASH", a: "GREEN", b: "WHITEWASH", clue: "When a company pretends to care about the environment more than it does" },
  { word: "GROWLER", a: "GROWL", b: "HOWLER", clue: "A reusable jug you bring to the tap room for craft beer" },
  { word: "HACKTIVIST", a: "HACKER", b: "ACTIVIST", clue: "Someone who breaks into systems to make a political point" },
  { word: "INFLIGHT", a: "INFORMATION", b: "FLIGHT", clue: "Entertainment or services experienced while airborne" },
  { word: "INTERROBANG", a: "INTERROGATION", b: "BANG", clue: "The punctuation mark that is both a question and an exclamation ?!" },
  { word: "JACKALOPE", a: "JACKRABBIT", b: "ANTELOPE", clue: "A mythical horned rabbit of American folklore" },
  { word: "JAZZERCISE", a: "JAZZ", b: "EXERCISE", clue: "A dance fitness class set to upbeat music" },
  { word: "LABRADOODLE", a: "LABRADOR", b: "POODLE", clue: "A fluffy designer dog bred from two popular breeds" },
  { word: "LIGER", a: "LION", b: "TIGER", clue: "The offspring of a lion and a tigress — largest of the big cats" },
  { word: "MANSPLAIN", a: "MAN", b: "EXPLAIN", clue: "To explain something to someone in a condescending, unsolicited way" },
  { word: "METROSEXUAL", a: "METROPOLITAN", b: "SEXUAL", clue: "A city-dwelling man with a keen interest in grooming and fashion" },
  { word: "MUGGLE", a: "MUG", b: "MUNDANE", clue: "Someone with no magical ability — a term J.K. Rowling made famous" },
  { word: "PIXEL", a: "PICTURE", b: "ELEMENT", clue: "The tiniest dot of colour that makes up a digital image" },
  { word: "SEXTING", a: "SEX", b: "TEXTING", clue: "Sending flirtatious or explicit messages by phone" },
  { word: "SHOPAHOLIC", a: "SHOPPING", b: "ALCOHOLIC", clue: "Someone with an uncontrollable urge to buy things" },
];
