const PUZZLES = [
  { word: "RACECAR", clue: "A high-speed vehicle on the track", extra: "7 letters" },
  { word: "LEVEL", clue: "Perfectly flat and even", extra: "5 letters" },
  { word: "CIVIC", clue: "Relating to a city or its citizens", extra: "5 letters" },
  { word: "RADAR", clue: "A system that detects objects using radio waves", extra: "5 letters" },
  { word: "NOON", clue: "The middle of the day", extra: "4 letters" },
  { word: "KAYAK", clue: "A narrow boat you paddle", extra: "5 letters" },
  { word: "REFER", clue: "To direct someone to another source", extra: "5 letters" },
  { word: "MADAM", clue: "A polite term for a woman", extra: "5 letters" },
  { word: "TENET", clue: "A core belief or principle", extra: "5 letters" },
  { word: "REPAPER", clue: "To put new wallpaper on walls", extra: "7 letters" },
  { word: "MOM", clue: "She raised you", extra: "3 letters" },
  { word: "DAD", clue: "Father figure", extra: "3 letters" },
  { word: "POP", clue: "A fizzy drink — or another word for dad", extra: "3 letters" },
  { word: "EWE", clue: "A female sheep", extra: "3 letters" },
  { word: "ROTATOR", clue: "Something that spins around an axis", extra: "7 letters" },
  { word: "DEED", clue: "A legal document, or a worthy act", extra: "4 letters" },
  { word: "PEEP", clue: "To look secretly through a small opening", extra: "4 letters" },
  { word: "SEES", clue: "What a working eye does", extra: "4 letters" },
  { word: "TOOT", clue: "A short blast on a horn or whistle", extra: "4 letters" },
  { word: "ROTOR", clue: "A rotating part in an engine or helicopter", extra: "5 letters" },
  { word: "SOLOS", clue: "Performances done entirely alone", extra: "5 letters" },
  { word: "STATS", clue: "Short for statistics", extra: "5 letters" },
  { word: "MINIM", clue: "A half note in music notation", extra: "5 letters" },
  { word: "SAGAS", clue: "Long stories of heroic adventure", extra: "5 letters" },
  { word: "REDDER", clue: "More intensely red in color", extra: "6 letters" },
  { word: "DEIFIED", clue: "Worshipped or treated as a god", extra: "7 letters" },
  { word: "REVIVER", clue: "Something that restores energy or life", extra: "7 letters" },
  { word: "NUN", clue: "A woman who has taken religious vows", extra: "3 letters" },
  { word: "PUP", clue: "A young dog", extra: "3 letters" },
  { word: "BIB", clue: "A cloth tucked under a baby's chin at mealtimes", extra: "3 letters" },
  { word: "GAG", clue: "A joke, or to choke", extra: "3 letters" },
  { word: "GIG", clue: "A live music performance", extra: "3 letters" },
  { word: "PEP", clue: "Lively spirit and energy", extra: "3 letters" },
  { word: "BOB", clue: "A short haircut; also to nod up and down", extra: "3 letters" },
  { word: "MUM", clue: "British English for mother", extra: "3 letters" },
  { word: "WOW", clue: "An exclamation of amazement", extra: "3 letters" },
];
